# Generated by Django 4.0.4 on 2022-04-30 05:34

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='description',
        ),
    ]
